name: HomographyNet
channels:
  - pytorch
  - fastai
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2021.11
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.6.3
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-project=0.8.4
  - anyio=3.5.0
  - appdirs=1.4.4
  - argcomplete=1.12.1
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=0.13.1
  - asn1crypto=1.4.0
  - astroid=2.4.2
  - astropy=4.0.2
  - async-timeout=3.0.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.2.0
  - autopep8=1.5.4
  - babel=2.8.0
  - backcall=0.2.0
  - backports=1.0
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.9.3
  - binaryornot=0.4.4
  - bitarray=1.6.0
  - bkcharts=0.2
  - black=19.10b0
  - blas=1.0
  - bleach=3.2.1
  - blosc=1.21.0
  - bokeh=2.2.3
  - boto=2.49.0
  - boto3=1.9.66
  - botocore=1.12.67
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.10.14
  - cachetools=4.1.1
  - cairo=1.16.0
  - catalogue=2.0.6
  - certifi=2020.6.20
  - cffi=1.14.3
  - cfitsio=3.470
  - chardet=3.0.4
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda=4.9.0
  - conda-content-trust=0.1.1
  - conda-package-handling=1.7.2
  - conda-token=0.3.0
  - contextlib2=0.6.0.post1
  - cookiecutter=1.7.2
  - cryptography=3.1.1
  - cudatoolkit=10.2.89
  - curl=7.71.1
  - cycler=0.10.0
  - cymem=2.0.3
  - cython=0.29.21
  - cython-blis=0.4.1
  - cytoolz=0.11.0
  - daal4py=2021.4.0
  - dal=2021.4.0
  - dask=2.30.0
  - dask-core=2.30.0
  - dataclasses=0.7
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - distributed=2.30.0
  - docutils=0.16
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.10
  - fastai=2.5.3
  - fastcache=1.1.0
  - fastcore=1.3.26
  - fastdownload=0.0.5
  - fastprogress=1.0.0
  - ffmpeg=4.3
  - filelock=3.0.12
  - flake8=3.9.2
  - flask=1.1.2
  - fontconfig=2.13.1
  - fonttools=4.16.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - fsspec=0.8.3
  - get_terminal_size=1.0.0
  - gevent=20.9.0
  - gh=1.5.0
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - gmp=6.1.2
  - gmpy2=2.0.8
  - gnutls=3.6.5
  - google-api-core=1.22.2
  - google-auth=1.22.1
  - google-cloud-core=1.4.3
  - google-cloud-storage=1.32.0
  - google-crc32c=1.0.0
  - google-resumable-media=1.1.0
  - googleapis-common-protos=1.52.0
  - graphite2=1.3.14
  - greenlet=0.4.17
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=2.10
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib_metadata=2.0.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=5.6.4
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.18.1
  - jeepney=0.4.3
  - jinja2=2.11.2
  - jinja2-time=0.2.0
  - jmespath=0.10.0
  - joblib=0.17.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyter_server=1.13.5
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keyring=21.4.0
  - kiwisolver=1.2.0
  - krb5=1.18.2
  - lame=3.100
  - langcodes=3.3.0
  - lazy-object-proxy=1.4.3
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.4.2
  - libcrc32c=1.1.1
  - libcurl=7.71.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - liblief=0.10.1
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - llvmlite=0.34.0
  - locket=0.2.0
  - lxml=4.6.1
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.2
  - more-itertools=8.5.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=3.3.2
  - mpmath=1.1.0
  - msgpack-python=1.0.0
  - multidict=4.7.6
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - murmurhash=1.0.2
  - mypy_extensions=0.4.3
  - nbclassic=0.2.6
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - nettle=3.4.1
  - networkx=2.5
  - nltk=3.5
  - nose=1.3.7
  - notebook=6.1.4
  - numba=0.51.2
  - numexpr=2.8.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - numpydoc=1.1.0
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.3.0
  - openpyxl=3.0.5
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.3
  - pandoc=2.11
  - pandocfilters=1.4.2
  - pango=1.45.3
  - parso=0.8.0
  - partd=1.1.0
  - patchelf=0.12
  - path=15.0.0
  - path.py=12.5.0
  - pathlib2=2.3.5
  - pathspec=0.7.0
  - pathtools=0.1.2
  - pathy=0.6.0
  - patsy=0.5.1
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.0
  - pip=20.2.4
  - pixman=0.40.0
  - pkginfo=1.6.0
  - pluggy=0.13.1
  - ply=3.11
  - poyo=0.5.0
  - preshed=3.0.2
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.13.0.1
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - py=1.9.0
  - py-lief=0.10.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycrypto=2.6.1
  - pycurl=7.43.0.6
  - pydantic=1.8.2
  - pydocstyle=5.1.1
  - pyerfa=2.0.0
  - pyflakes=2.3.1
  - pygments=2.7.1
  - pylint=2.6.0
  - pyls-spyder=0.4.0
  - pyodbc=4.0.30
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.1.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python-libarchive-c=2.9
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=4.0.1
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyxdg=0.26
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.3
  - qtconsole=5.2.2
  - qtpy=1.9.0
  - readline=8.0
  - regex=2020.10.15
  - requests=2.24.0
  - ripgrep=12.1.1
  - rope=0.18.0
  - rsa=4.6
  - rtree=0.9.7
  - ruamel_yaml=0.15.87
  - s3transfer=0.1.13
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scikit-learn-intelex=2021.4.0
  - scipy=1.7.3
  - seaborn=0.11.0
  - secretstorage=3.1.2
  - send2trash=1.5.0
  - setuptools=50.3.0
  - shellingham=1.3.1
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.24
  - six=1.15.0
  - smart_open=5.1.0
  - snappy=1.1.8
  - sniffio=1.1.0
  - snowballstemmer=2.0.0
  - sortedcollections=1.2.1
  - sortedcontainers=2.2.2
  - soupsieve=2.0.1
  - spacy=3.2.1
  - spacy-legacy=3.0.8
  - spacy-loggers=1.0.1
  - sphinx=3.2.1
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.4
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlalchemy=1.3.19
  - sqlite=3.33.0
  - srsly=2.4.1
  - statsmodels=0.12.0
  - sympy=1.6.2
  - tbb=2021.5.0
  - tbb4py=2020.3
  - tblib=1.7.0
  - terminado=0.9.1
  - testpath=0.4.4
  - text-unidecode=1.3
  - textdistance=4.2.1
  - thinc=8.0.13
  - threadpoolctl=2.1.0
  - three-merge=0.1.1
  - tifffile=2020.10.1
  - tinycss=0.4
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.11.1
  - torchvision=0.11.3
  - tornado=6.1
  - tqdm=4.50.2
  - traitlets=5.0.5
  - typed-ast=1.4.1
  - typer=0.4.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - ujson=4.0.1
  - unicodecsv=0.14.1
  - unicodedata2=13.0.0.post2
  - unidecode=1.1.1
  - unixodbc=2.3.9
  - urllib3=1.24.3
  - wasabi=0.8.2
  - watchdog=0.10.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - werkzeug=1.0.1
  - wheel=0.35.1
  - whichcraft=0.6.1
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=2.0.1
  - xlrd=1.2.0
  - xlsxwriter=1.3.7
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - yarl=1.5.1
  - zeromq=4.3.3
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.3.1
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.1.2
  - zstd=1.4.9
  - pip:
    - absl-py==1.0.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - importlib-metadata==4.11.0
    - markdown==3.3.6
    - natsort==8.1.0
    - oauthlib==3.2.0
    - opencv-contrib-python==3.4.2.17
    - requests-oauthlib==1.3.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - torch-summary==1.4.5
    - torch-tb-profiler==0.4.0
